# USA

In [ ]:
!pip install -q openai backoff gpt-cost-estimator

In [ ]:
import pandas as pd
import os
from google.colab import drive
drive.mount('/content/drive')
import time
from tqdm.auto import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from gpt_cost_estimator import CostEstimator
import openai
from openai import OpenAI
from google.colab import userdata
import backoff
import random
from sklearn.model_selection import train_test_split
import json
import traceback
import re
import glob

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/pro_vip_usa.csv')
df = df.rename(columns={'body': 'posttext'})
examples_df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/Eva/USA/learn_df_usa_1.csv', sep = ";")
examples_df = examples_df.rename(columns={'body': 'posttext'})
if "processed" not in df.columns:
    df["processed"] = 0

<ipython-input-14-0746e996fa82>:1: DtypeWarning: Columns (19,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/pro_vip_usa.csv')

In [ ]:
df

,id,post_source_domain,thread_id,parent_id,posttext,author,author_fullname,author_avatar_url,timestamp,type,...,num_likes,num_comments,num_media,location_name,location_latlong,location_city,unix_timestamp,SourceFile,"id,post_source_domain,thread_id,parent_id,body,author,author_fullname,author_avatar_url,timestamp,type,url,image_url,media_url,hashtags,num_likes,num_comments,num_media,location_name,location_latlong,location_city,unix_timestamp",processed
0,DBJOdsau9Er,https://www.instagram.com/taylorswift/,DBJOdsau9Er,DBJOdsau9Er,We’ll be kicking off the final leg of The Eras...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-10-15 12:19:57,video,...,3649950.0,0.0,1.0,NaN,NaN,NaN,1.728995e+09,swift,NaN,0
1,C57qcCPucLV,https://www.instagram.com/taylorswift/,C57qcCPucLV,C57qcCPucLV,It’s a 2am surprise: The Tortured Poets Depart...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-04-19 06:00:57,photo,...,7033707.0,0.0,1.0,NaN,NaN,NaN,1.713506e+09,swift,NaN,0
2,C57c1DWMkf_,https://www.instagram.com/taylorswift/,C57c1DWMkf_,C57c1DWMkf_,The Tortured Poets Department. An anthology of...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-04-19 04:02:02,photo,...,10225231.0,0.0,5.0,NaN,NaN,NaN,1.713499e+09,swift,NaN,0
3,DC1r0NKOqPQ,https://www.instagram.com/taylorswift/,DC1r0NKOqPQ,DC1r0NKOqPQ,Our 6 shows in Toronto were so incredible. It ...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-11-26 15:00:06,photo,...,4977698.0,0.0,16.0,NaN,NaN,NaN,1.732633e+09,swift,NaN,0
4,DCcGiXHOW7V,https://www.instagram.com/taylorswift/,DCcGiXHOW7V,DCcGiXHOW7V,Just 13 days til The Tortured Poets Department...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-11-16 16:33:20,photo,...,3122862.0,0.0,1.0,NaN,NaN,NaN,1.731775e+09,swift,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170129,KGFlL6oDj3,https://www.instagram.com/danbilzerian/,KGFlL6oDj3,KGFlL6oDj3,NaN,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:05:10,photo,...,15055.0,338.0,1.0,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,0
170130,KGFe2poDj0,https://www.instagram.com/danbilzerian/,KGFe2poDj0,KGFe2poDj0,Yea I guess it's stuck,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:04:18,photo,...,14592.0,382.0,1.0,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,0
170131,KGFabPoDjy,https://www.instagram.com/danbilzerian/,KGFabPoDjy,KGFabPoDjy,NaN,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:03:42,photo,...,24617.0,1422.0,1.0,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,0
170132,KGFVPVoDjv,https://www.instagram.com/danbilzerian/,KGFVPVoDjv,KGFVPVoDjv,NaN,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:03:00,photo,...,30663.0,2045.0,1.0,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,0
170133,KGFP-zIDjq,https://www.instagram.com/danbilzerian/,KGFP-zIDjq,KGFP-zIDjq,Gator hunting,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:02:17,photo,...,38135.0,4082.0,1.0,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,0

In [ ]:
api_key_name =
api_key =

client = OpenAI(
    api_key=api_key
)

@CostEstimator()
def query_openai(model, messages, mock=True, completion_tokens=10):
    return client.chat.completions.create(
                      model=model,
                      messages=messages,
                      max_tokens=600)

@backoff.on_exception(backoff.expo, (openai.RateLimitError, openai.APIError))
def run_request(system_prompt, user_prompt, model, mock):
  messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": user_prompt}
  ]

  return query_openai(
          model=model,
          messages=messages,
          mock=mock
        )

In [ ]:
# Erstellung Example-Learn-Text
category_names = [
    "Person",
    "Inhalt",
    "Partei"
]

def extract_categories(row):
    categories = [category_names[i] for i, cat in enumerate(row[24:28]) if cat == 1]
    return ", ".join(categories)

example_text = "\n\n".join(
    f"posttext: {row['posttext']}\nHashtags: {row['hashtags']}\nKategorien: {extract_categories(row)}"
    for index, row in examples_df.iterrows()
)

In [ ]:
len(example_text)

318178

In [ ]:
system_prompt = """

Du bist ein fortgeschrittenes KI-Modell zur Klassifikation. Deine Aufgabe ist es zu entscheiden ob die Texte aus Instagrambeiträgen von prominenten Personen einen politischen Inhalt haben oder nicht. Ziel der Untersuchung ist es, zu verstehen, inwiefern Promis in Sozialen Medien politisch kommunizieren und welche Handlungsstrategien hier verfolgt werden.

Bei der Klassifikation sollen die Beiträge in die folgenden drei Kategorien klassifiziert werden, Mehrfachnennungen sind möglich, ein Post kann mehrere Kategorien abbilden:

1. Person: Die Kategorie trifft zu, wenn im Text ein:e Poltiker:in erwähnt und positiv oder negativ bewertet wird oder unterstützt wird. Erwähnungen und Taggings über das @-Symbol von Personen, die nicht als Politiker bekannt sind, sollten nicht als Politiker:in klassifiziert werden. Bitte immer genau prüfen ob die Person wirklich als Politiker:in beaknnt ist.

2. Inhalt: Die Kategorie trifft zu, wenn im Text ein politisches Thema erwähnt und positiv oder negativ bewertet wird oder unterstützt wird. Allgemeine Motivationssprüche oder Lebensweisheiten ohne politischen Bezug sollten nicht als politischer Inhalt klassifiziert werden.

3. Partei: Die Kategorie trifft zu, wenn im Text eine politische Partei erwähnt und positiv oder negativ bewertet wird oder unterstützt wird.

Hier sind einige klassifizierte Beispiele:
{example_text}

Bei der Klassifikation bekommst du den Text des Beitrags und die Hashtags zur Verfügung gestellt. Deine Aufgabe ist es zu entscheiden, ob die Kategorien 1-3 im Post vorliegen. Wenn die betreffende Kategorie vorliegt, soll eine Eins in der Zelle gesetzt werden. Wenn keine der Kategorien zutrifft, wird bei allen drei Kategorien eine Null gesetzt.

"""

In [ ]:
prompt = """
Bitte klassifiziere den folgenden Instagram-Post in die folgenden Kategorien:

1. Person: Wenn eine Politiker:in erwähnt und positiv oder negativ bewertet wird.
2. Inhalt: Wenn ein politisches Thema erwähnt oder unterstützt wird.
3. Partei: Wenn eine politische Partei erwähnt oder unterstützt wird.

Gib die Antwort **ausschließlich** im folgenden JSON-Format zurück:
{
    "Person": 0 oder 1,
    "Inhalt": 0 oder 1,
    "Partei": 0 oder 1
}

Posttext: "[posttext]"
Hashtags: "[hashtags]"
"""

In [ ]:
CostEstimator.DEFAULT_PRICES['gpt-4o-mini'] = {
    'input': 0.15 / 1000,
    'output': 0.60 / 1000
}

MOCK = False
RESET_COST = True
SAMPLE_SIZE = 0
MODEL = "gpt-4o-mini"
SAVE_INTERVAL = 500  # Speichern nach 2000 Beiträgen

# **📂 Speicherort**
save_path = "/content/drive/MyDrive/Projekt_VIP/Data/Class/USA"
full_dataset_path = os.path.join(save_path, "full_dataset.csv")

categories = ["Person", "Inhalt", "Partei"]

# **📥 Falls vorhanden: Fortschritt laden, sonst Originaldatei**
if os.path.exists(full_dataset_path):
    df = pd.read_csv(full_dataset_path)
    print(f"Fortgesetzte Verarbeitung: Geladen aus {full_dataset_path} mit {len(df)} Zeilen.")
else:
    df = df
    df["processed"] = 0  # NEUE SPALTE: Verarbeitungsstatus
    print(f"Neue Verarbeitung: Geladen mit {len(df)} Zeilen.")

# Sicherstellen, dass die Kategorien existieren
for category in categories:
    if category not in df.columns:
        df[category] = 0

# **🚀 Letzte gespeicherte Datei suchen**
existing_files = glob.glob(os.path.join(save_path, "class_*_final_df_pv.csv"))
existing_numbers = []
pattern = re.compile(r"class_(\d+)_final_df_pv\.csv")  # Nummer aus Dateinamen extrahieren

for f in existing_files:
    match = pattern.search(f)
    if match:
        existing_numbers.append(int(match.group(1)))

# Setze Dateinummer auf die nächste verfügbare
file_counter = max(existing_numbers) + 1 if existing_numbers else 1

# **🔍 Unbearbeitete Beiträge filtern**
filtered_df = df[df["processed"] == 0].copy()

if SAMPLE_SIZE > 0:
    SAMPLE_SIZE = min(SAMPLE_SIZE, len(filtered_df))
    filtered_df = filtered_df.sample(SAMPLE_SIZE)

# **🌟 Verarbeitung starten**
if not filtered_df.empty:
    batch = []
    for index, row in tqdm(filtered_df.iterrows(), total=len(filtered_df)):
        try:
            p = prompt.replace('[posttext]', str(row['posttext'])).replace('[hashtags]', str(row['hashtags']))
            response = run_request(system_prompt, p, MODEL, MOCK)

            if not MOCK:
                response_content = response.choices[0].message.content.strip()

                try:
                    result_dict = json.loads(response_content)

                    for category in categories:
                        df.at[index, category] = result_dict.get(category, 0)

                    df.at[index, "processed"] = 1  # ✅ Beitrag als verarbeitet markieren

                except json.JSONDecodeError:
                    print(f"Fehler beim Parsen der Antwort: {response_content}")

            batch.append(index)

            # **📁 Zwischenspeicherung nach jedem Batch (2000 Beiträge)**
            if len(batch) >= SAVE_INTERVAL:
                file_path = os.path.join(save_path, f"class_{file_counter}_final_df_pv.csv")
                df.iloc[batch].to_csv(file_path, index=False)
                print(f"Zwischenspeicherung abgeschlossen: {file_path}")

                # **✅ Fortschritt regelmäßig sichern!**
                df.to_csv(full_dataset_path, index=False)
                print(f"Fortschritt gespeichert: {full_dataset_path}")

                batch.clear()
                file_counter += 1

        except Exception as e:
            print(f"Ein Fehler ist aufgetreten: {e}")
            traceback.print_exc()

    # **Letzte Batch speichern**
    if batch:
        file_path = os.path.join(save_path, f"class_{file_counter}_final_df_pv.csv")
        df.iloc[batch].to_csv(file_path, index=False)
        print(f"Letzte Zwischenspeicherung abgeschlossen: {file_path}")

        df.to_csv(full_dataset_path, index=False)
        print(f"Finaler Fortschritt gespeichert: {full_dataset_path}")

else:
    print("Keine neuen Beiträge zu verarbeiten.")

print("✅ Verarbeitung abgeschlossen.")

<ipython-input-21-d4ab33538e24>:20: DtypeWarning: Columns (19,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_dataset_path)

Fortgesetzte Verarbeitung: Geladen aus /content/drive/MyDrive/Projekt_VIP/Data/Class/USA/full_dataset.csv mit 170134 Zeilen.

  0%|          | 0/4214 [00:00<?, ?it/s]

Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.

In [ ]:
final_df = df[(df['processed'] == 1)]
final_df

,id,post_source_domain,thread_id,parent_id,posttext,author,author_fullname,author_avatar_url,timestamp,type,...,location_name,location_latlong,location_city,unix_timestamp,SourceFile,"id,post_source_domain,thread_id,parent_id,body,author,author_fullname,author_avatar_url,timestamp,type,url,image_url,media_url,hashtags,num_likes,num_comments,num_media,location_name,location_latlong,location_city,unix_timestamp",processed,Person,Inhalt,Partei
0,DBJOdsau9Er,https://www.instagram.com/taylorswift/,DBJOdsau9Er,DBJOdsau9Er,We’ll be kicking off the final leg of The Eras...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-10-15 12:19:57,video,...,NaN,NaN,NaN,1.728995e+09,swift,NaN,1,0,0,0
1,C57qcCPucLV,https://www.instagram.com/taylorswift/,C57qcCPucLV,C57qcCPucLV,It’s a 2am surprise: The Tortured Poets Depart...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-04-19 06:00:57,photo,...,NaN,NaN,NaN,1.713506e+09,swift,NaN,1,0,0,0
2,C57c1DWMkf_,https://www.instagram.com/taylorswift/,C57c1DWMkf_,C57c1DWMkf_,The Tortured Poets Department. An anthology of...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-04-19 04:02:02,photo,...,NaN,NaN,NaN,1.713499e+09,swift,NaN,1,0,0,0
3,DC1r0NKOqPQ,https://www.instagram.com/taylorswift/,DC1r0NKOqPQ,DC1r0NKOqPQ,Our 6 shows in Toronto were so incredible. It ...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-11-26 15:00:06,photo,...,NaN,NaN,NaN,1.732633e+09,swift,NaN,1,0,0,0
4,DCcGiXHOW7V,https://www.instagram.com/taylorswift/,DCcGiXHOW7V,DCcGiXHOW7V,Just 13 days til The Tortured Poets Department...,taylorswift,Taylor Swift,https://scontent-fra5-1.cdninstagram.com/v/t51...,2024-11-16 16:33:20,photo,...,NaN,NaN,NaN,1.731775e+09,swift,NaN,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170129,KGFlL6oDj3,https://www.instagram.com/danbilzerian/,KGFlL6oDj3,KGFlL6oDj3,NaN,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:05:10,photo,...,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,1,0,0,0
170130,KGFe2poDj0,https://www.instagram.com/danbilzerian/,KGFe2poDj0,KGFe2poDj0,Yea I guess it's stuck,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:04:18,photo,...,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,1,0,0,0
170131,KGFabPoDjy,https://www.instagram.com/danbilzerian/,KGFabPoDjy,KGFabPoDjy,NaN,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:03:42,photo,...,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,1,0,0,0
170132,KGFVPVoDjv,https://www.instagram.com/danbilzerian/,KGFVPVoDjv,KGFVPVoDjv,NaN,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:03:00,photo,...,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,1,0,0,0
170133,KGFP-zIDjq,https://www.instagram.com/danbilzerian/,KGFP-zIDjq,KGFP-zIDjq,Gator hunting,danbilzerian,Dan Bilzerian,https://scontent-fra3-1.cdninstagram.com/v/t51...,2012-05-01 19:02:17,photo,...,NaN,NaN,NaN,1.335899e+09,bilzerian,NaN,1,0,0,0

# POL

In [ ]:
!pip install -q openai backoff gpt-cost-estimator

In [ ]:
import pandas as pd
import os
from google.colab import drive
drive.mount('/content/drive')
import time
from tqdm.auto import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from gpt_cost_estimator import CostEstimator
import openai
from openai import OpenAI
from google.colab import userdata
import backoff
import random
from sklearn.model_selection import train_test_split
import json
import traceback
import re
import glob

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/POL/final_df_btw_class.csv')
examples_df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/POL/EVA/learn_pol_usa_5.csv', sep = ";")
if "processed" not in df.columns:
    df["processed"] = 0

In [ ]:
api_key_name = "dere"
api_key = "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"

client = OpenAI(
    api_key=api_key
)

@CostEstimator()
def query_openai(model, messages, mock=True, completion_tokens=10):
    return client.chat.completions.create(
                      model=model,
                      messages=messages,
                      max_tokens=600)

@backoff.on_exception(backoff.expo, (openai.RateLimitError, openai.APIError))
def run_request(system_prompt, user_prompt, model, mock):
  messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": user_prompt}
  ]

  return query_openai(
          model=model,
          messages=messages,
          mock=mock
        )

In [ ]:
# Erstellung Example-Learn-Text
category_names = [
   "vip"
]

def extract_categories(row):
    categories = [category_names[i] for i, cat in enumerate(row[24:28]) if cat == 1]
    return ", ".join(categories)

example_text = "\n\n".join(
    f"body: {row['body']}\nHashtags: {row['hashtags']}\nKategorien: {extract_categories(row)}"
    for index, row in examples_df.iterrows()
)

In [ ]:
len(example_text)

559975

In [ ]:
kon_text = """
Beispiele:

1.
Posttext: "Vielen Dank an Sängerin Lea, die gestern Abend auf ihrem Konzert klar gesagt hat: 'Geht wählen und unterstützt Anna Müller – sie steht für unsere Zukunft!' 🎤💪"
Hashtags: #Lea #AnnaMüller #Vote
Antwort: {"prominente_unterstützung": 1}

2.
Posttext: "Der ehemalige Nationalspieler Max Mustermann hat heute ein Statement veröffentlicht: 'Ich wähle Peter Schmidt, weil er sich für den Sport stark macht.' ⚽️🔥"
Hashtags: #MaxMustermann #PeterSchmidt #Sport
Antwort: {"prominente_unterstützung": 1}

3.
Posttext: "Gestern war Schauspielerin Julia Becker bei unserer Wahlkampfveranstaltung dabei. Auf der Bühne sagte sie: 'Ich unterstütze die Politik von Sabine Hoffmann und bitte euch alle, sie am Sonntag zu wählen!' 🎬🙌"
Hashtags: #JuliaBecker #SabineHoffmann #Wahl2025
Antwort: {"prominente_unterstützung": 1}
"""

In [ ]:
system_prompt = """
Du bist ein fortgeschrittenes KI-Modell zur Klassifikation. Deine Aufgabe ist es zu entscheiden, ob in den Texten aus Instagram-Beiträgen von Politiker:innen die Unterstützung oder eine Wahlempfehlung durch eine prominente Person deutlich wird.

Unter "prominente Person" verstehen wir Personen, die in der Öffentlichkeit bekannt sind, z. B. aus den Bereichen Unterhaltung, Sport, Kultur, Wissenschaft oder Medien. Politiker:innen selbst zählen nicht als Prominente.

Eine bloße Erwähnung einer prominenten Person reicht nicht aus. Unterstützung liegt nur vor, wenn die prominente Person ausdrücklich oder implizit den/die Politiker:in oder Partei positiv bewertet, unterstützt, der Partei beitritt oder zur Wahl aufruft.

Hier sind einige klassifizierte Beispiele:
{example_text}

Außerdem hier noch ein paar konstruierte Beispiele, die als prominente Unterstützung gelten können:
{kon_text}

Bei der Klassifikation bekommst du den Text des Beitrags und die Hashtags zur Verfügung gestellt.
Deine Aufgabe: Entscheide, ob prominente Unterstützung vorliegt.
"""

In [ ]:
prompt = """
Bitte klassifiziere den folgenden Instagram-Post nach folgender Kategorie:

VIP: Es wird deutlich, dass eine prominente Person ihre Unterstützung für Partei, Inhalt oder Person deutlich macht oder sogar eine Wahlempfehlung gibt.

Gib die Antwort **ausschließlich** im folgenden JSON-Format zurück:
{
    "vip": 0 oder 1
}

Posttext: "[body]"
Hashtags: "[hashtags]"
"""

In [ ]:
# Preise konfigurieren
CostEstimator.DEFAULT_PRICES['gpt-4o-mini'] = {
    'input': 0.15 / 1000,
    'output': 0.60 / 1000
}

MOCK = False
RESET_COST = True
SAMPLE_SIZE = 0
MODEL = "gpt-4o-mini"
SAVE_INTERVAL = 50  # Speichern nach 500 Beiträgen

# 📂 Speicherort
save_path = "/content/drive/MyDrive/Projekt_VIP/Data/POL/Class/"
full_dataset_path = os.path.join(save_path, "full_dataset.csv")

# Kategorie festlegen
category = "vip"

# 📥 Falls vorhanden: Fortschritt laden, sonst Originaldatei
if os.path.exists(full_dataset_path):
    df = pd.read_csv(full_dataset_path)
    print(f"Fortgesetzte Verarbeitung: Geladen aus {full_dataset_path} mit {len(df)} Zeilen.")
else:
    df = df
    df["processed"] = 0  # NEUE SPALTE: Verarbeitungsstatus
    print(f"Neue Verarbeitung: Geladen mit {len(df)} Zeilen.")

# Sicherstellen, dass die Kategorie existiert
if category not in df.columns:
    df[category] = 0

# 🔁 Kostenberechnung zurücksetzen
if RESET_COST:
    CostEstimator.reset()
    print("Reset Cost Estimation")

# 🔍 Letzte gespeicherte Datei suchen
existing_files = glob.glob(os.path.join(save_path, "class_*_final_df_pv.csv"))
existing_numbers = []
pattern = re.compile(r"class_(\d+)_final_df_pv\.csv")

for f in existing_files:
    match = pattern.search(f)
    if match:
        existing_numbers.append(int(match.group(1)))

file_counter = max(existing_numbers) + 1 if existing_numbers else 1

# 🔍 Unbearbeitete Beiträge filtern
filtered_df = df[df["processed"] == 0].copy()

if SAMPLE_SIZE > 0:
    SAMPLE_SIZE = min(SAMPLE_SIZE, len(filtered_df))
    filtered_df = filtered_df.sample(SAMPLE_SIZE)

# 🌟 Verarbeitung starten
if not filtered_df.empty:
    batch = []
    for index, row in tqdm(filtered_df.iterrows(), total=len(filtered_df)):
        try:
            # Prompt mit den Post-Daten befüllen
            p = prompt.replace('[body]', str(row['body'])).replace('[hashtags]', str(row['hashtags']))
            response = run_request(system_prompt, p, MODEL, MOCK)

            if not MOCK:
                response_content = response.choices[0].message.content.strip()

                try:
                    result_dict = json.loads(response_content)
                    df.at[index, category] = result_dict.get(category, 0)
                    df.at[index, "processed"] = 1  # Beitrag als verarbeitet markieren

                except json.JSONDecodeError:
                    print(f"Fehler beim Parsen der Antwort: {response_content}")

            batch.append(index)

            # 📁 Zwischenspeicherung nach jedem Batch
            if len(batch) >= SAVE_INTERVAL:
                file_path = os.path.join(save_path, f"class_{file_counter}_final_df_pv.csv")
                df.iloc[batch].to_csv(file_path, index=False)
                print(f"Zwischenspeicherung abgeschlossen: {file_path}")

                df.to_csv(full_dataset_path, index=False)
                print(f"Fortschritt gespeichert: {full_dataset_path}")

                batch.clear()
                file_counter += 1

        except Exception as e:
            import traceback
            print(f"Ein Fehler ist aufgetreten: {e}")
            traceback.print_exc()

    # Letzte Batch speichern
    if batch:
        file_path = os.path.join(save_path, f"class_{file_counter}_final_df_pv.csv")
        df.iloc[batch].to_csv(file_path, index=False)
        print(f"Letzte Zwischenspeicherung abgeschlossen: {file_path}")

        df.to_csv(full_dataset_path, index=False)
        print(f"Finaler Fortschritt gespeichert: {full_dataset_path}")

else:
    print("Keine neuen Beiträge zu verarbeiten.")

print("✅ Verarbeitung abgeschlossen.")

Fortgesetzte Verarbeitung: Geladen aus /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/full_dataset.csv mit 149499 Zeilen.
Reset Cost Estimation

  0%|          | 0/453 [00:00<?, ?it/s]

Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Zwischenspeicherung abgeschlossen: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/class_618_final_df_pv.csv
Fortschritt gespeichert: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/full_dataset.csv
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Zwischenspeicherung abgeschlossen: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/class_619_final_df_pv.csv
Fortschritt gespeichert: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/full_dataset.csv
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Zwischenspeicherung abgeschlossen: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/class_620_final_df_pv.csv
Fortschritt gespeichert: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/full_dataset.csv
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Fehler beim Parsen der Antwort: ```json
{
    "vip": 0
}
```
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Zwischenspeicherung abgeschlossen: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/class_621_final_df_pv.csv
Fortschritt gespeichert: /content/drive/MyDrive/Projekt_VIP/Data/POL/Class/full_dataset.csv
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Fehler beim Parsen der Antwort: ```json
{
    "vip": 0
}
```
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.

In [ ]:
final_df = df[(df['processed'] == 1)]
final_df

,id,id_scraping,post_source_domain,author,author_fullname,timestamp,unix_timestamp,type,url,body,...,state,party,list_position,electoral_district_number,job_group,electoral_district_name,acc_type,acc_name,processed,vip
0,DGaimNLImWU,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-23T12:05:38Z,1740312338,photo,https://www.instagram.com/p/DGaimNLImWU,Für die Freiheit ❌❌💛✨✅,...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
1,DGXwCDoogzO,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-22T10:05:00Z,1740218700,photo,https://www.instagram.com/p/DGXwCDoogzO,"Ihr Lieben, morgen ist Wahl und ich hoffe ihr ...",...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
2,DGVdlrJIJ6a,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-21T12:45:00Z,1740141900,photo,https://www.instagram.com/p/DGVdlrJIJ6a,Weil du es dir irgendwann ja auch mal gewünsch...,...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
3,DGSj2FHoVsj,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-20T09:42:36Z,1740044556,photo,https://www.instagram.com/p/DGSj2FHoVsj,"Móin ✨ Es ist Zeit, dass Selbstständige und Gr...",...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
4,DGNomEqoNmJ,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-18T11:47:55Z,1739879275,photo,https://www.instagram.com/p/DGNomEqoNmJ,Verhandlungen über den Frieden in Europa darf ...,...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149902,DGLkclZoXQJ,3176,https://www.instagram.com/saschamueller_mdb/,frederic_sascha.mueller,Frederic (Sascha) Müller,2025-02-17T16:33:11Z,1739809991,photo,https://www.instagram.com/p/DGLkclZoXQJ,Als Kreis- & Gemeinderat habe ich mich bewusst...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149903,DF0i_7HtbkD,3176,https://www.instagram.com/saschamueller_mdb/,cla.woller.greenstuff,Claudia Woller,2025-02-08T17:58:00Z,1739037480,photo,https://www.instagram.com/p/DF0i_7HtbkD,Am 23. Februar wird gewählt. Wir haben heute a...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149904,DFfWZyXKUt6,3176,https://www.instagram.com/saschamueller_mdb/,gruenepassau,Grüne Passau-Stadt,2025-01-31T12:23:54Z,1738326234,photo,https://www.instagram.com/p/DFfWZyXKUt6,Lust auf einen spannenden Abend voller Frauen...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149905,DFaCptUPxpD,3176,https://www.instagram.com/saschamueller_mdb/,gruenepassau,Grüne Passau-Stadt,2025-01-29T10:55:06Z,1738148106,photo,https://www.instagram.com/p/DFaCptUPxpD,"Unser Bundestagskandidat Frederic-Alexej ""Sasc...",...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149906,DFSOs7PtWyB,3176,https://www.instagram.com/saschamueller_mdb/,gruenepassau,Grüne Passau-Stadt,2025-01-26T10:06:28Z,1737885988,photo,https://www.instagram.com/p/DFSOs7PtWyB,🌟 Passau im Fokus: Bei einer spannenden Diskus...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0

Warning: Total number of columns (39) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (149907) exceeds max_rows (20000). Limiting to first (20000) rows.
Warning: Total number of columns (39) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (149907) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
fail_df = df[(df['processed'] == 0)]
fail_df

Empty DataFrame
Columns: [id, id_scraping, post_source_domain, author, author_fullname, timestamp, unix_timestamp, type, url, body, hashtags, likes_hidden, num_likes, num_comments, num_media, num_followers, interaction_rate, location_name, location_latlong, location_city, missing_fields, filename_image, name, surnames, sex, birth_year, postal_code, residence, job, state, party, list_position, electoral_district_number, job_group, electoral_district_name, acc_type, acc_name, processed, vip]
Index: []

[0 rows x 39 columns]

In [ ]:
vip_df = df[(df['vip'] == 1)]
vip_df

,id,id_scraping,post_source_domain,author,author_fullname,timestamp,unix_timestamp,type,url,body,...,state,party,list_position,electoral_district_number,job_group,electoral_district_name,acc_type,acc_name,processed,vip
104,DGFjz58un08,741,https://www.instagram.com/olfbs/,carsten.mueller_mdb,Carsten Müller,2025-02-15T08:43:55Z,1739609035,video,https://www.instagram.com/p/DGFjz58un08,#Freie #Wähler #Braunschweig rufen auf: #ERSTS...,...,NI,FREIE WÄHLER,14.0,50.0,27.0,Braunschweig,candidate,olfbs,1,1
131,DGWM9BbtrWr,745,https://www.instagram.com/benjamin.stern.wob/,jusoswolfsburg,Jusos UB Wolfsburg,2025-02-21T19:39:32Z,1740166772,photo,https://www.instagram.com/p/DGWM9BbtrWr,Mit @benjamin.stern.spd gibt es keine schlecht...,...,NI,SPD,27.0,51.0,71.0,Helmstedt – Wolfsburg,candidate,benjamin.stern.wob,1,1
145,DGPisD4ITB4,745,https://www.instagram.com/benjamin.stern.wob/,immacolata.glosemeyer,Immacolata Glosemeyer,2025-02-19T05:38:27Z,1739943507,video,https://www.instagram.com/p/DGPisD4ITB4,Bei der Bundestagswahl am 23. Februar wähle ic...,...,NI,SPD,27.0,51.0,71.0,Helmstedt – Wolfsburg,candidate,benjamin.stern.wob,1,1
158,DGGaHeOtoyY,745,https://www.instagram.com/benjamin.stern.wob/,spd_boldecker_land,SPD Boldecker Land,2025-02-15T16:28:41Z,1739636921,video,https://www.instagram.com/p/DGGaHeOtoyY,Tulpen statt Eisblumen. Auf alle Menschen zuge...,...,NI,SPD,27.0,51.0,71.0,Helmstedt – Wolfsburg,candidate,benjamin.stern.wob,1,1
327,DGQxQwXP9Kw,746,https://www.instagram.com/alexander.jordan.cdu/,alexander.jordan.cdu,Alexander Jordan,2025-02-19T17:02:02Z,1739984522,video,https://www.instagram.com/p/DGQxQwXP9Kw,🚗 Eine starke Stimme für unsere Region!\n\n@ti...,...,NI,CDU,22.0,51.0,26.0,Helmstedt – Wolfsburg,candidate,alexander.jordan.cdu,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149487,DGMJAKBsvpQ,618,https://www.instagram.com/marcoschulzelg/,marcoschulzelg,Marco Schulze,2025-02-17T21:55:34Z,1739829334,video,https://www.instagram.com/p/DGMJAKBsvpQ,Klare Wahlempfehlung von Philipp Amthor! 🚀 Dr....,...,NI,CDU,27.0,37.0,27.0,Lüchow-Dannenberg – Lüneburg,candidate,marcoschulzelg,1,1
149492,DGC564qseM6,618,https://www.instagram.com/marcoschulzelg/,marcoschulzelg,Marco Schulze,2025-02-14T07:58:17Z,1739519897,video,https://www.instagram.com/p/DGC564qseM6,Ein spannender und aufschlussreicher Tag mit @...,...,NI,CDU,27.0,37.0,27.0,Lüchow-Dannenberg – Lüneburg,candidate,marcoschulzelg,1,1
149636,DFsPl0PNSZp,619,https://www.instagram.com/j_verlinden/,wendlandgruene,Die Wendlandgrünen,2025-02-05T12:34:29Z,1738758869,photo,https://www.instagram.com/p/DFsPl0PNSZp,„Ich bin den Grünen beigetreten wegen des Femi...,...,NI,GRÜNE,3.0,37.0,42.0,Lüchow-Dannenberg – Lüneburg,candidate,j_verlinden,1,1
149710,DGYl8H5N7W6,676,https://www.instagram.com/je.ssi.ca_p/,djenadh,Djenabou Diallo Hartmann,2025-02-22T17:56:21Z,1740246981,photo,https://www.instagram.com/p/DGYl8H5N7W6,Heute nochmal Alles gegeben in Langenhagen und...,...,NI,GRÜNE,17.0,43.0,91.0,Hannover-Land I,candidate,je.ssi.ca_p,1,1
149714,DGXgu1KsJW3,676,https://www.instagram.com/je.ssi.ca_p/,gruene_garbsen,Grüne Garbsen,2025-02-22T07:51:36Z,1740210696,photo,https://www.instagram.com/p/DGXgu1KsJW3,klasse das wir gestern nochmal gemeinsam Haust...,...,NI,GRÜNE,17.0,43.0,91.0,Hannover-Land I,candidate,je.ssi.ca_p,1,1

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/POL/final_df_btw_class.csv')

df.to_excel("/content/drive/MyDrive/Projekt_VIP/Data/POL/final_df_btw_class.xlsx", index=False)

In [ ]:
df

,id,id_scraping,post_source_domain,author,author_fullname,timestamp,unix_timestamp,type,url,body,...,state,party,list_position,electoral_district_number,job_group,electoral_district_name,acc_type,acc_name,processed,vip
0,DGaimNLImWU,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-23T12:05:38Z,1740312338,photo,https://www.instagram.com/p/DGaimNLImWU,Für die Freiheit ❌❌💛✨✅,...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
1,DGXwCDoogzO,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-22T10:05:00Z,1740218700,photo,https://www.instagram.com/p/DGXwCDoogzO,"Ihr Lieben, morgen ist Wahl und ich hoffe ihr ...",...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
2,DGVdlrJIJ6a,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-21T12:45:00Z,1740141900,photo,https://www.instagram.com/p/DGVdlrJIJ6a,Weil du es dir irgendwann ja auch mal gewünsch...,...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
3,DGSj2FHoVsj,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-20T09:42:36Z,1740044556,photo,https://www.instagram.com/p/DGSj2FHoVsj,"Móin ✨ Es ist Zeit, dass Selbstständige und Gr...",...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
4,DGNomEqoNmJ,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-18T11:47:55Z,1739879275,photo,https://www.instagram.com/p/DGNomEqoNmJ,Verhandlungen über den Frieden in Europa darf ...,...,NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149902,DGLkclZoXQJ,3176,https://www.instagram.com/saschamueller_mdb/,frederic_sascha.mueller,Frederic (Sascha) Müller,2025-02-17T16:33:11Z,1739809991,photo,https://www.instagram.com/p/DGLkclZoXQJ,Als Kreis- & Gemeinderat habe ich mich bewusst...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149903,DF0i_7HtbkD,3176,https://www.instagram.com/saschamueller_mdb/,cla.woller.greenstuff,Claudia Woller,2025-02-08T17:58:00Z,1739037480,photo,https://www.instagram.com/p/DF0i_7HtbkD,Am 23. Februar wird gewählt. Wir haben heute a...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149904,DFfWZyXKUt6,3176,https://www.instagram.com/saschamueller_mdb/,gruenepassau,Grüne Passau-Stadt,2025-01-31T12:23:54Z,1738326234,photo,https://www.instagram.com/p/DFfWZyXKUt6,Lust auf einen spannenden Abend voller Frauen...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149905,DFaCptUPxpD,3176,https://www.instagram.com/saschamueller_mdb/,gruenepassau,Grüne Passau-Stadt,2025-01-29T10:55:06Z,1738148106,photo,https://www.instagram.com/p/DFaCptUPxpD,"Unser Bundestagskandidat Frederic-Alexej ""Sasc...",...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0
149906,DFSOs7PtWyB,3176,https://www.instagram.com/saschamueller_mdb/,gruenepassau,Grüne Passau-Stadt,2025-01-26T10:06:28Z,1737885988,photo,https://www.instagram.com/p/DFSOs7PtWyB,🌟 Passau im Fokus: Bei einer spannenden Diskus...,...,BY,GRÜNE,52.0,228.0,83.0,Passau,candidate,saschamueller_mdb,1,0

Quellen:

Achmann-Denkler, M. (2024). michaelachmann/social-media-lab: DOI Release (v0.0.12). Zenodo. https://doi.org/10.5281/zenodo.10618621

Achmann-Denkler, M. (2024). “Text Classification.” January 22, 2024. https://doi.org/10.5281/zenodo.10039756.