# Hypo 1

In [ ]:
from google.colab import drive
import pandas as pd
import os
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_ubersicht_usa = pd.read_excel('/content/drive/MyDrive/Projekt_VIP/Data/VIP/übersicht.xlsx', sheet_name=1)

In [ ]:
df_ubersicht_usa

,Platz,Name,Accountname,Beiträge,Follower,Link,Kategorie,Unnamed: 7,Gesamt,170134
0,1,Selena Gomez,selenagomez,2030,423199562,https://www.instagram.com/selenagomez/,Musik,NaN,NaN,NaN
1,2,Kylie Jenner,kyliejenner,7134,395800504,https://www.instagram.com/kyliejenner/,Influencer,NaN,NaN,NaN
2,3,Dwayne Johnson,therock,7985,395143386,https://www.instagram.com/therock/,TV,NaN,NaN,NaN
3,4,Ariana Grande,arianagrande,296,376578488,https://www.instagram.com/arianagrande/,Musik,NaN,NaN,NaN
4,5,Kim Kardashian,kimkardashian,6321,359368091,https://www.instagram.com/kimkardashian/,Influencer,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63,64,Addison Easterling,addisonraee,112,34262641,https://www.instagram.com/addisonraee/,Influencer,NaN,NaN,NaN
64,65,Mike Tyson,miketyson,1604,34136409,https://www.instagram.com/miketyson/,Sport,NaN,NaN,NaN
65,66,Curtis James Jackson,50cent,1265,33910593,https://www.instagram.com/50cent/,Musik,NaN,NaN,NaN
66,67,Megan Pete,theestallion,560,32750100,https://www.instagram.com/theestallion/,Musik,NaN,NaN,NaN
67,68,Dan Bilzerian,danbilzerian,1380,31176301,https://www.instagram.com/danbilzerian/,Influencer,NaN,NaN,NaN

In [ ]:
df_ubersicht_ger = pd.read_excel('/content/drive/MyDrive/Projekt_VIP/Data/VIP/übersicht.xlsx', sheet_name=0)

In [ ]:
df_usa = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/VIP/full_dataset_usa.csv', sep = ";")

/tmp/ipython-input-1381224128.py:1: DtypeWarning: Columns (19,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_usa = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/VIP/full_dataset_usa.csv', sep = ";")

In [ ]:
df_ger = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/VIP/full_dataset_ger.csv', sep = ";")

In [ ]:
df_ger

,id,post_source_domain,thread_id,parent_id,posttext,author,author_fullname,author_avatar_url,timestamp,type,...,Person,Inhalt,Partei,Unnamed: 26,PersonR,InhaltR,ParteiR,B-Person,B-Inhalt,B-Partei
0,DAbDNweotAm,https://www.instagram.com/toni.kr8s/,DAbDNweotAm,DAbDNweotAm,It was great shooting the new fall/winter coll...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,27.09.2024 13:42,photo,...,0,0,0,NaN,0,0,0,0,0,0
1,DAYfA-jIbf4,https://www.instagram.com/toni.kr8s/,DAYfA-jIbf4,DAYfA-jIbf4,I’m thrilled to share the new @marcopolo Fall ...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,26.09.2024 13:53,video,...,0,0,0,NaN,0,0,0,0,0,0
2,DATK3VHtrtz,https://www.instagram.com/toni.kr8s/,DATK3VHtrtz,DATK3VHtrtz,Drei Mittelfeld-Regisseure unter sich 😮‍💨\n\nU...,theiconleague,𝚃𝚑𝚎 𝙸𝚌𝚘𝚗 𝙻𝚎𝚊𝚐𝚞𝚎,https://scontent-fra5-1.cdninstagram.com/v/t51...,24.09.2024 12:15,photo,...,0,0,0,NaN,0,0,0,0,0,0
3,DAQLfZTIPw1,https://www.instagram.com/toni.kr8s/,DAQLfZTIPw1,DAQLfZTIPw1,Recap 😎 👉🏼 Summer Season 2024\nKnapp 15 Coachi...,toni.kr8s_academy,TONI KROOS ACADEMY,https://scontent-fra3-1.cdninstagram.com/v/t51...,23.09.2024 08:33,video,...,0,0,0,1.0,1,0,0,1,0,0
4,C_2-uKhtBAn,https://www.instagram.com/toni.kr8s/,C_2-uKhtBAn,C_2-uKhtBAn,¡Puertas abiertas! La nueva Toni Kroos Academy...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,13.09.2024 13:30,photo,...,0,0,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169328,MOQWy8gxwc,https://www.instagram.com/dianazurloewen/,MOQWy8gxwc,MOQWy8gxwc,on my way to a camping trip.,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-23 16:16:01,photo,...,0,0,0,NaN,0,0,0,0,0,0
169329,MLCrDzAx5S,https://www.instagram.com/dianazurloewen/,MLCrDzAx5S,MLCrDzAx5S,chai latte,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-22 10:18:45,photo,...,0,0,0,NaN,0,0,0,0,0,0
169330,MJFznLAx2G,https://www.instagram.com/dianazurloewen/,MJFznLAx2G,MJFznLAx2G,Love my dog :),dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-21 16:07:38,photo,...,0,0,0,NaN,0,0,0,0,0,0
169331,MIclFnAx2O,https://www.instagram.com/dianazurloewen/,MIclFnAx2O,MIclFnAx2O,waiting for my friend to arrive at home. Haven...,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-21 10:07:28,photo,...,0,0,0,NaN,0,0,0,0,0,0
169332,MHDW6agx9F,https://www.instagram.com/dianazurloewen/,MHDW6agx9F,MHDW6agx9F,Werbung | new shoe love-nike air max,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-20 21:07:47,photo,...,0,0,0,NaN,0,0,0,0,0,0

In [ ]:
# Erstelle ein Dictionary, das die Accountnamen den Followerzahlen zuordnet
follower_mapping = dict(zip(df_ubersicht_usa['Accountname'], df_ubersicht_usa['Follower']))

# Füge eine neue Spalte "Followerzahl" in df_usa hinzu und fülle sie mit den Werten aus dem Dictionary
df_usa['Followerzahl'] = df_usa['author'].map(follower_mapping)

In [ ]:
# Erstelle ein Dictionary, das die Accountnamen den Followerzahlen zuordnet
follower_mapping = dict(zip(df_ubersicht_ger['Accountname'], df_ubersicht_ger['Follower']))

# Füge eine neue Spalte "Followerzahl" in df_usa hinzu und fülle sie mit den Werten aus dem Dictionary
df_ger['Followerzahl'] = df_ger['author'].map(follower_mapping)

In [ ]:
df_ger

,id,post_source_domain,thread_id,parent_id,posttext,author,author_fullname,author_avatar_url,timestamp,type,...,Inhalt,Partei,Unnamed: 26,PersonR,InhaltR,ParteiR,B-Person,B-Inhalt,B-Partei,Followerzahl
0,DAbDNweotAm,https://www.instagram.com/toni.kr8s/,DAbDNweotAm,DAbDNweotAm,It was great shooting the new fall/winter coll...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,27.09.2024 13:42,photo,...,0,0,NaN,0,0,0,0,0,0,48911127.0
1,DAYfA-jIbf4,https://www.instagram.com/toni.kr8s/,DAYfA-jIbf4,DAYfA-jIbf4,I’m thrilled to share the new @marcopolo Fall ...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,26.09.2024 13:53,video,...,0,0,NaN,0,0,0,0,0,0,48911127.0
2,DATK3VHtrtz,https://www.instagram.com/toni.kr8s/,DATK3VHtrtz,DATK3VHtrtz,Drei Mittelfeld-Regisseure unter sich 😮‍💨\n\nU...,theiconleague,𝚃𝚑𝚎 𝙸𝚌𝚘𝚗 𝙻𝚎𝚊𝚐𝚞𝚎,https://scontent-fra5-1.cdninstagram.com/v/t51...,24.09.2024 12:15,photo,...,0,0,NaN,0,0,0,0,0,0,NaN
3,DAQLfZTIPw1,https://www.instagram.com/toni.kr8s/,DAQLfZTIPw1,DAQLfZTIPw1,Recap 😎 👉🏼 Summer Season 2024\nKnapp 15 Coachi...,toni.kr8s_academy,TONI KROOS ACADEMY,https://scontent-fra3-1.cdninstagram.com/v/t51...,23.09.2024 08:33,video,...,0,0,1.0,1,0,0,1,0,0,NaN
4,C_2-uKhtBAn,https://www.instagram.com/toni.kr8s/,C_2-uKhtBAn,C_2-uKhtBAn,¡Puertas abiertas! La nueva Toni Kroos Academy...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,13.09.2024 13:30,photo,...,0,0,NaN,0,0,0,0,0,0,48911127.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169328,MOQWy8gxwc,https://www.instagram.com/dianazurloewen/,MOQWy8gxwc,MOQWy8gxwc,on my way to a camping trip.,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-23 16:16:01,photo,...,0,0,NaN,0,0,0,0,0,0,1243220.0
169329,MLCrDzAx5S,https://www.instagram.com/dianazurloewen/,MLCrDzAx5S,MLCrDzAx5S,chai latte,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-22 10:18:45,photo,...,0,0,NaN,0,0,0,0,0,0,1243220.0
169330,MJFznLAx2G,https://www.instagram.com/dianazurloewen/,MJFznLAx2G,MJFznLAx2G,Love my dog :),dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-21 16:07:38,photo,...,0,0,NaN,0,0,0,0,0,0,1243220.0
169331,MIclFnAx2O,https://www.instagram.com/dianazurloewen/,MIclFnAx2O,MIclFnAx2O,waiting for my friend to arrive at home. Haven...,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-21 10:07:28,photo,...,0,0,NaN,0,0,0,0,0,0,1243220.0
169332,MHDW6agx9F,https://www.instagram.com/dianazurloewen/,MHDW6agx9F,MHDW6agx9F,Werbung | new shoe love-nike air max,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-20 21:07:47,photo,...,0,0,NaN,0,0,0,0,0,0,1243220.0

In [ ]:
df_ger_filtered = df_ger[df_ger['Followerzahl'].isna()]

In [ ]:
df_ger_filtered

,id,post_source_domain,thread_id,parent_id,posttext,author,author_fullname,author_avatar_url,timestamp,type,...,Inhalt,Partei,Unnamed: 26,PersonR,InhaltR,ParteiR,B-Person,B-Inhalt,B-Partei,Followerzahl
2,DATK3VHtrtz,https://www.instagram.com/toni.kr8s/,DATK3VHtrtz,DATK3VHtrtz,Drei Mittelfeld-Regisseure unter sich 😮‍💨\n\nU...,theiconleague,𝚃𝚑𝚎 𝙸𝚌𝚘𝚗 𝙻𝚎𝚊𝚐𝚞𝚎,https://scontent-fra5-1.cdninstagram.com/v/t51...,24.09.2024 12:15,photo,...,0,0,NaN,0,0,0,0,0,0,NaN
3,DAQLfZTIPw1,https://www.instagram.com/toni.kr8s/,DAQLfZTIPw1,DAQLfZTIPw1,Recap 😎 👉🏼 Summer Season 2024\nKnapp 15 Coachi...,toni.kr8s_academy,TONI KROOS ACADEMY,https://scontent-fra3-1.cdninstagram.com/v/t51...,23.09.2024 08:33,video,...,0,0,1.0,1,0,0,1,0,0,NaN
5,C_2MqQQsDN2,https://www.instagram.com/toni.kr8s/,C_2MqQQsDN2,C_2MqQQsDN2,"Erfolg wird erarbeitet, nicht durch Glück oder...",maschmeyer,Carsten Maschmeyer,https://scontent-fra3-1.cdninstagram.com/v/t51...,13.09.2024 06:12,photo,...,0,0,NaN,0,0,0,0,0,0,NaN
6,C_gVU26Iaca,https://www.instagram.com/toni.kr8s/,C_gVU26Iaca,C_gVU26Iaca,Nominated for the 2024 Men’s Ballon d’Or\n\nTo...,ballondorofficial,Ballon d’Or,https://scontent-fra5-1.cdninstagram.com/v/t51...,04.09.2024 18:25,photo,...,0,0,NaN,0,0,0,0,0,0,NaN
8,C_dZs_ZoLo5,https://www.instagram.com/toni.kr8s/,C_dZs_ZoLo5,C_dZs_ZoLo5,@toni.kr8s showing his class at @theiconleague...,433,433,https://scontent-fra5-1.cdninstagram.com/v/t51...,03.09.2024 15:11,video,...,0,0,NaN,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165335,CcBAiMgAI03,https://www.instagram.com/dianazurloewen/,CcBAiMgAI03,CcBAiMgAI03,Zuhause sieht für jeden anders aus & ist auch ...,kisu,👸🏼Kisu,https://scontent-fra5-2.cdninstagram.com/v/t51...,2022-04-06 16:09:40,video,...,0,0,NaN,0,0,0,0,0,0,NaN
165364,CaRqNkCAphE,https://www.instagram.com/dianazurloewen/,CaRqNkCAphE,CaRqNkCAphE,Warum lösen wir Konflikte heute noch immer mit...,kristina_lunz,Kristina Lunz,https://scontent-fra3-1.cdninstagram.com/v/t51...,2022-02-22 10:19:52,video,...,1,0,NaN,0,1,0,0,0,0,NaN
165377,CZtgFsHlmbb,https://www.instagram.com/dianazurloewen/,CZtgFsHlmbb,CZtgFsHlmbb,Heute bei 4 Grad und Regen was für die ✨ menta...,marenschiller,Maren Schiller,https://scontent-fra5-1.cdninstagram.com/v/t51...,2022-02-08 09:21:10,video,...,0,0,NaN,0,0,0,0,0,0,NaN
165394,CYmAuA1Pkt6,https://www.instagram.com/dianazurloewen/,CYmAuA1Pkt6,CYmAuA1Pkt6,"Heute wieder was für die #mentalheath ✨ tun, i...",marenschiller,Maren Schiller,https://scontent-fra5-1.cdninstagram.com/v/t51...,2022-01-11 15:01:33,video,...,0,0,NaN,0,0,0,0,0,0,NaN
165419,CXa3AwGlO33,https://www.instagram.com/dianazurloewen/,CXa3AwGlO33,CXa3AwGlO33,Du fragst dich „Was kann ich als Einzelne:r sc...,leavenoonebehind2020,#LeaveNoOneBehind,https://scontent-fra5-1.cdninstagram.com/v/t51...,2021-12-13 10:31:53,video,...,1,0,NaN,1,1,0,1,0,0,NaN

In [ ]:
df_usa['interaction_rate'] = (df_usa['num_comments'] + df_usa['num_likes']) / df_usa['Followerzahl']

In [ ]:
df_ger['interaction_rate'] = (df_ger['num_comments'] + df_ger['num_likes']) / df_ger['Followerzahl']

In [ ]:
from scipy import stats

# Unterteile den DataFrame in zwei Gruppen basierend auf der Variable "Inhalt"
gruppe_1 = df_usa[df_usa['Inhalt'] == 1]['interaction_rate']
gruppe_0 = df_usa[df_usa['Inhalt'] == 0]['interaction_rate']

# Führe den T-Test durch
t_statistic, p_value = stats.ttest_ind(gruppe_1, gruppe_0)

# Gib die Ergebnisse aus
print(f"T-Statistik: {t_statistic}")
print(f"P-Wert: {p_value}")

T-Statistik: nan
P-Wert: nan

In [ ]:
df_ger = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/full_dataset_ger.csv', sep = ";")

In [ ]:
df_usa.to_csv('/content/drive/MyDrive/Projekt_VIP/Data/df_usa_final.csv', index=False)

In [ ]:
df_usa['neue_spalte'] = ((df_usa['Person'] == 1) | (df_usa['Inhalt'] == 1) | (df_usa['Partei'] == 1)).astype(int)

In [ ]:
df_ger['neue_spalte'] = ((df_ger['Person'] == 1) | (df_ger['Inhalt'] == 1) | (df_ger['Partei'] == 1)).astype(int)

In [ ]:
anzahl_einsen = df_usa['neue_spalte'].value_counts()[1]
print(f"Die 1 kommt in der Spalte 'neue_spalte' {anzahl_einsen} Mal vor.")

Die 1 kommt in der Spalte 'neue_spalte' 5334 Mal vor.

In [ ]:
anzahl_einsen = df_ger['neue_spalte'].value_counts()[1]
print(f"Die 1 kommt in der Spalte 'neue_spalte' {anzahl_einsen} Mal vor.")

Die 1 kommt in der Spalte 'neue_spalte' 2925 Mal vor.

In [ ]:
df_ger

,id,post_source_domain,thread_id,parent_id,posttext,author,author_fullname,author_avatar_url,timestamp,type,...,Unnamed: 26,PersonR,InhaltR,ParteiR,B-Person,B-Inhalt,B-Partei,neue_spalte,Followerzahl,interaction_rate
0,DAbDNweotAm,https://www.instagram.com/toni.kr8s/,DAbDNweotAm,DAbDNweotAm,It was great shooting the new fall/winter coll...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,27.09.2024 13:42,photo,...,NaN,0,0,0,0,0,0,0,48911127.0,0.020440
1,DAYfA-jIbf4,https://www.instagram.com/toni.kr8s/,DAYfA-jIbf4,DAYfA-jIbf4,I’m thrilled to share the new @marcopolo Fall ...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,26.09.2024 13:53,video,...,NaN,0,0,0,0,0,0,0,48911127.0,0.000887
2,DATK3VHtrtz,https://www.instagram.com/toni.kr8s/,DATK3VHtrtz,DATK3VHtrtz,Drei Mittelfeld-Regisseure unter sich 😮‍💨\n\nU...,theiconleague,𝚃𝚑𝚎 𝙸𝚌𝚘𝚗 𝙻𝚎𝚊𝚐𝚞𝚎,https://scontent-fra5-1.cdninstagram.com/v/t51...,24.09.2024 12:15,photo,...,NaN,0,0,0,0,0,0,0,NaN,NaN
3,DAQLfZTIPw1,https://www.instagram.com/toni.kr8s/,DAQLfZTIPw1,DAQLfZTIPw1,Recap 😎 👉🏼 Summer Season 2024\nKnapp 15 Coachi...,toni.kr8s_academy,TONI KROOS ACADEMY,https://scontent-fra3-1.cdninstagram.com/v/t51...,23.09.2024 08:33,video,...,1.0,1,0,0,1,0,0,0,NaN,NaN
4,C_2-uKhtBAn,https://www.instagram.com/toni.kr8s/,C_2-uKhtBAn,C_2-uKhtBAn,¡Puertas abiertas! La nueva Toni Kroos Academy...,toni.kr8s,Toni Kroos,https://scontent-fra5-1.cdninstagram.com/v/t51...,13.09.2024 13:30,photo,...,NaN,0,0,0,0,0,0,0,48911127.0,0.015763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169328,MOQWy8gxwc,https://www.instagram.com/dianazurloewen/,MOQWy8gxwc,MOQWy8gxwc,on my way to a camping trip.,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-23 16:16:01,photo,...,NaN,0,0,0,0,0,0,0,1243220.0,0.000318
169329,MLCrDzAx5S,https://www.instagram.com/dianazurloewen/,MLCrDzAx5S,MLCrDzAx5S,chai latte,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-22 10:18:45,photo,...,NaN,0,0,0,0,0,0,0,1243220.0,0.000253
169330,MJFznLAx2G,https://www.instagram.com/dianazurloewen/,MJFznLAx2G,MJFznLAx2G,Love my dog :),dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-21 16:07:38,photo,...,NaN,0,0,0,0,0,0,0,1243220.0,0.000356
169331,MIclFnAx2O,https://www.instagram.com/dianazurloewen/,MIclFnAx2O,MIclFnAx2O,waiting for my friend to arrive at home. Haven...,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-21 10:07:28,photo,...,NaN,0,0,0,0,0,0,0,1243220.0,0.000658
169332,MHDW6agx9F,https://www.instagram.com/dianazurloewen/,MHDW6agx9F,MHDW6agx9F,Werbung | new shoe love-nike air max,dianazurloewen,Diana,https://scontent-fra5-1.cdninstagram.com/v/t51...,2012-06-20 21:07:47,photo,...,NaN,0,0,0,0,0,0,0,1243220.0,0.000607

In [ ]:
# Filtern Sie den DataFrame, um nur Zeilen mit 'neue_spalte' == 1 zu erhalten
df_gefiltert = df_usa[df_usa['neue_spalte'] == 1]

# Berechnen Sie den Mittelwert der 'interaction_rate' in den gefilterten Zeilen
mittelwert_interaction_rate = df_gefiltert['interaction_rate'].mean()

# Geben Sie den Mittelwert aus
print(f"Der Mittelwert der Interaction Rate für Zeilen mit pol. Inhalt ist: {mittelwert_interaction_rate}")


# Filtern Sie den DataFrame, um nur Zeilen mit 'neue_spalte' == 1 zu erhalten
df_gefiltert = df_usa[df_usa['neue_spalte'] == 0]

# Berechnen Sie den Mittelwert der 'interaction_rate' in den gefilterten Zeilen
mittelwert_interaction_rate = df_gefiltert['interaction_rate'].mean()

# Geben Sie den Mittelwert aus
print(f"Der Mittelwert der Interaction Rate für Zeilen ohne pol. Inhalt ist: {mittelwert_interaction_rate}")

Der Mittelwert der Interaction Rate für Zeilen mit pol. Inhalt ist: 0.005318466700704423
Der Mittelwert der Interaction Rate für Zeilen ohne pol. Inhalt ist: 0.005986577504793516

In [ ]:
# Filtern Sie den DataFrame, um nur Zeilen mit 'neue_spalte' == 1 zu erhalten
df_gefiltert = df_ger[df_ger['neue_spalte'] == 1]

# Berechnen Sie den Mittelwert der 'interaction_rate' in den gefilterten Zeilen
mittelwert_interaction_rate = df_gefiltert['interaction_rate'].mean()

# Geben Sie den Mittelwert aus
print(f"Der Mittelwert der Interaction Rate für Zeilen mit pol. Inhalt ist: {mittelwert_interaction_rate}")

# Filtern Sie den DataFrame, um nur Zeilen mit 'neue_spalte' == 1 zu erhalten
df_gefiltert = df_ger[df_ger['neue_spalte'] == 0]

# Berechnen Sie den Mittelwert der 'interaction_rate' in den gefilterten Zeilen
mittelwert_interaction_rate = df_gefiltert['interaction_rate'].mean()

# Geben Sie den Mittelwert aus
print(f"Der Mittelwert der Interaction Rate für Zeilen ohne pol. Inhalt ist: {mittelwert_interaction_rate}")

Der Mittelwert der Interaction Rate für Zeilen mit pol. Inhalt ist: 0.013913095607212085
Der Mittelwert der Interaction Rate für Zeilen ohne pol. Inhalt ist: 0.015959352836114576